/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DrStockFinder {
    }
    interface DrStockPrice {
        "stockSymbol": string;
    }
}
export interface DrStockFinderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDrStockFinderElement;
}
declare global {
    interface HTMLDrStockFinderElement extends Components.DrStockFinder, HTMLStencilElement {
    }
    var HTMLDrStockFinderElement: {
        prototype: HTMLDrStockFinderElement;
        new (): HTMLDrStockFinderElement;
    };
    interface HTMLDrStockPriceElement extends Components.DrStockPrice, HTMLStencilElement {
    }
    var HTMLDrStockPriceElement: {
        prototype: HTMLDrStockPriceElement;
        new (): HTMLDrStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "dr-stock-finder": HTMLDrStockFinderElement;
        "dr-stock-price": HTMLDrStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface DrStockFinder {
        "onUcSymbolSelected"?: (event: DrStockFinderCustomEvent<string>) => void;
    }
    interface DrStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "dr-stock-finder": DrStockFinder;
        "dr-stock-price": DrStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dr-stock-finder": LocalJSX.DrStockFinder & JSXBase.HTMLAttributes<HTMLDrStockFinderElement>;
            "dr-stock-price": LocalJSX.DrStockPrice & JSXBase.HTMLAttributes<HTMLDrStockPriceElement>;
        }
    }
}
